### PR TITLE
Geosci labs

### LINKED ISSUE #108: Mag_Induced2D crashes
Error:
```
/srv/conda/lib/python3.7/site-packages/gpgLabs/Mag/Simulator.py in plotMagSurvey2D(survey, a, b, npts, data, pred, fig, ax, vmin, vmax)
    216 
    217     # Use SimPEG.PF ploting function
--> 218     PF.Magnetics.plot_obs_2D(rxLoc, d=data, fig=fig,  ax=ax,
    219                              vmin=vmin, vmax=vmax,
    220                              marker=False, cmap='RdBu_r')

AttributeError: module 'SimPEG.PF.Magnetics' has no attribute 'plot_obs_2D'
```

has `PF.Magnetics.plot_obs_2D` moved to `Utils.PlotUtils.plot2Ddata`?

### PR DESCRIPTION
**Pull request by lheagy**
Follow the [geosci-labs](https://github.com/geoscixyz/geosci-labs) repository for maintaining the notebooks. The maintenance strategy now follows that outlined in [geosci-course](https://github.com/geoscixyz/geosci-course)
- the `.jupyter-include` file contains the list of notebooks that we copy-over from geosci-labs
- now the code that is imported is `geosci-labs`
- many thanks @orerocks for pointing out that this repo is lagging behind! 
   - This resolve #108, #109  

:wave: @thast, would you be willing to review this?

### CODE REVIEW

**Comment by thast** [comment]
Warning on `mybinder`. I will add it in this PR:
image

**Comment by lheagy** [comment]
Many thanks @thast! I will get to this over the weekend. Does the overall `nblibrarian` workflow make sense to you?

**Comment by thast** [comment]
I did not looked at `nlibrarian` too deeply yet. This is the `jupyter-include` file am I right? But I still see the notebooks being part of the `gpgLabs` repository on this branch. So I am unsure of what  `jupyter-include` does. I get we install the code (`*.py`) from `geosci-labs` but not how the notebooks are updated automatically?

**Comment by lheagy** [comment]
:wave: @thast: would you be willing to do another pass on this? I updated the links, so I believe it should be good to go unless you catch anything else. Thanks!

**Comment by lheagy** [comment]
Thanks @thast! It looks like you fixed the broken link :) and the `notebooks` directory is renamed in this pr to be lower-cased

image

**Pull request merged**
